
ht_main:
    resource: "@HTMainBundle/Resources/config/routing.yml"
    prefix:   /main

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation

login:
    path: /login
    defaults:
        _controller: HTUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

register:
    path: /register
    defaults:
        _controller: HTUserBundle:Security:register 
