ht_main_homepage:
    path:     /
    defaults: { _controller: HTMainBundle:Main:index }


ht_main_categories:
    path:    /categories
    defaults: { _controller: HTMainBundle:Main:categories }


ht_main_teas:
    path:    /teas/{id}
    defaults:
        _controller: HTMainBundle:Main:teas
    requirements:
        id: \d+

ht_main_user:
    path:    /user/{id}
    defaults:
        _controller: HTMainBundle:Main:user
    requirements:
        id: \d+

ht_main_team:
    path:    /team
    defaults: { _controller: HTMainBundle:Main:team }

ht_main_faq:
    path:    /FAQ
    defaults: { _controller: HTMainBundle:Main:faq }

ht_main_addSeller:
    path:    /addSeller
    defaults: { _controller: HTMainBundle:Main:addSeller }

ht_main_updateShop:
    path:   /updateShop/{id}
    defaults: { _controller: HTMainBundle:Main:updateSeller }
    requirements:
        id: \d+

ht_main_contact:
    path:   /contact
    defaults: { _controller: HTMainBundle:Main:contact }

ht_main_shopList:
    path:     /shopList
    defaults: { _controller: HTMainBundle:Main:shopList }

ht_main_shop:
    path:    /shop/{id}
    defaults:
        _controller: HTMainBundle:Main:shop
    requirements:
        id: \d+

ht_main_addProduct:
    path:   /addProduct
    defaults: { _controller: HTMainBundle:Main:addProduct }

ht_main_updateProduct:
    path:   /updateProduct/{id}
    defaults: { _controller: HTMainBundle:Main:updateProduct }
    requirements:
        id: \d+

ht_main_ajaxProduct:
    path: /ajaxProduct/{id}
    defaults: { _controller: HTMainBundle:Main:ajaxCallProduct }

ht_main_shopPage:
    path:    /shopPage/{id}
    defaults:
        _controller: HTMainBundle:Main:shopPage

    requirements:
        id: \d+

ht_main_sitemap:
    path:   /sitemap
    defaults: { _controller: HTMainBundle:Main:sitemap }

ht_main_fav:
    path:     /favAjax
    defaults: { _controller: HTMainBundle:Main:fav }

ht_main_removeFav:
    path:     /removeFavAjax
    defaults: { _controller: HTMainBundle:Main:removeFav }
