<?php

namespace HT\MainBundle\Repository;

/**
 * sellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sellerRepository extends \Doctrine\ORM\EntityRepository
{
}
